on: [push, pull_request]
jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: CC=gcc-10 CXX=g++-10 bazel build ... --config gcc

  linux-clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: CC=clang-12 CXX=clang++-12 bazel build ...

  linux-clang-asan:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: CC=clang-12 CXX=clang++-12 bazel build ... --config asan

  windows-msvc:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bazel build ...

  buildifier:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
          wget --output-document=buildifier https://github.com/bazelbuild/buildtools/releases/download/5.0.1/buildifier-linux-amd64
          sudo chmod +x buildifier
    - name: Check
      run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname "*.BUILD" -or -iname BUILD)

  linux-cmake:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install --no-install-recommends libasio-dev
    # Test the oldest supported CMake version.
    - run: pip install cmake==3.14.4.post1 && cmake --version
    - run: CC=gcc-10 CXX=g++-10 cmake -Wdev -Werror=dev -S . -B build
    - run: cmake --build build
    # Test the newest supported CMake version.
    - run: rm -rf build
    - run: pip install cmake==3.22.3 && cmake --version
    - run: CC=gcc-10 CXX=g++-10 cmake -Wdev -Werror=dev -S . -B build
    - run: cmake --build build
